version: "3"

services:
  web:
    build:
      context: .
    image: relaynode
    env_file: .env
    command: npm start
    volumes:
      - ./config:/app/config
    ports:
      - "5000:5000"

  relay:
    image: relaynode
    env_file: .env
    command: npm run relay